apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: spring-framework-petclinic
  annotations:
    github.com/project-slug: stevenmchaves/spring-framework-petclinic
spec:
  type: other
  lifecycle: unknown
  owner: guests
